import { parseSpec } from "@/utils/parseSpec";
import fs from "fs/promises";
import path from "path";
import type { ExportedHandlebarsTest } from "../types/tests";
import prettier from "prettier";
import { deleteAsync } from "del";

await deleteAsync("dist");
await fs.mkdir("dist");

const specTsFile = path.join("tests.mjs");
const testCases = await parseSpec();

await createJavaScriptSpec(specTsFile, testCases);

async function createJavaScriptSpec(
  file: string,
  testCases: ExportedHandlebarsTest[]
) {
  await fs.writeFile(
    file,
    prettier.format(generateJs(testCases), { parser: "typescript" })
  );
}

function generateJs(testCases: ExportedHandlebarsTest[]) {
  return `

// DO NOT EDIT THIS FILE MANUALLY
// generaty by ${path.relative(process.cwd(), __filename)}

export const handlebarsSpec = ${JSON.stringify(testCases)}

`;
}
