import { loadTestcases } from "@/utils/testcases";
import fs from "fs/promises";
import path from "path";
import prettier from "prettier";
import cp from "child_process";

const specMjsFile = path.join("tests.mjs");
const testCases = loadTestcases();

const jsCode = `
// DO NOT EDIT THIS FILE MANUALLY
// generate by ${path.relative(process.cwd(), __filename)}

export const handlebarsSpec = ${JSON.stringify(testCases)};

export default handlebarsSpec;
`;

const prettyCode = prettier.format(jsCode);
await fs.writeFile(specMjsFile, prettyCode);
cp.execSync("git add " + specMjsFile);
