import { loadTestcases } from "@/utils/testcases";
import fs from "fs/promises";
import path from "path";
import type { ExportedHandlebarsTest } from "../types/tests";
import prettier from "prettier";
import cp from "child_process";

const specTsFile = path.join("tests.mjs");
const testCases = await loadTestcases();

await createJavaScriptSpec(specTsFile, testCases);
cp.execSync("git add " + specTsFile);

async function createJavaScriptSpec(
  file: string,
  testCases: ExportedHandlebarsTest[]
) {
  await fs.writeFile(
    file,
    prettier.format(generateJs(testCases), { parser: "typescript" })
  );
}

function generateJs(testCases: ExportedHandlebarsTest[]) {
  return `

// DO NOT EDIT THIS FILE MANUALLY
// generate by ${path.relative(process.cwd(), __filename)}

export const handlebarsSpec = ${JSON.stringify(testCases)};

export default handlebarsSpec;

`;
}
