import { resolveSpecFile } from "./lib/specPath";
import { writeTestcase } from "./lib/writeTestcase";
import fs from "node:fs/promises";
import path from "path";
import { addResultToFile } from "./lib/addResultToFile";

const folder = "06-path-expression/invalid-ids";
const me = path.relative(process.cwd(), __filename);

const invalidChars =
  `! " # % & ' ( ) * + , ; < = > @ [ \\ ] ^ \` { | } ~`.split(" ");

for (const char of invalidChars) {
  const charCode = char.charCodeAt(0);
  const filename = `${folder}/char-code-${charCode}.hb-spec.json`;
  const resolvedFile = resolveSpecFile(filename);
  writeTestcase(resolvedFile, {
    $schema: "../../schema/testcase.json",
    type: "parseError",
    description: `${char} may not be used in an id`,
    template: `{{a${char}b}}`,
    expected: {
      message: `Parse error on line 1:\n{{a${char}b}}\n--^\nExpecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'`,
      line: 1,
      column: 3,
    },
  });
  addResultToFile(resolvedFile);
}

await fs.writeFile(
  resolveSpecFile(`${folder}/README.txt`),
  `WARNING: The files in this folder where GENERATED by "${me}"`
);
