import { resolveSpecFile } from "./lib/specPath";
import { writeTestcase } from "./lib/writeTestcase";
import fs from "node:fs/promises";
import path from "path";
import { addResultToFile } from "./lib/addResultToFile";
import { HandlebarsTest } from "../src/types/tests";

const folder = "06-path-expression/invalid-ids";
const me = path.relative(process.cwd(), __filename);

const invalidChars =
  `! " # % & ' ( ) * + , ; < = > @ [ \\ ] ^ \` { | } ~`.split(" ");

let indexFile = `# Testcases for invalid id characters

*Note: Parse error tests are not a core part of the spec. The important 
part is that an error is thrown in these cases, not the exact error message.* 
`;

for (const char of invalidChars) {
  const charCode = char.charCodeAt(0);
  const filename = `char-code-${charCode}.hb-spec.json`;
  const filepath = `${folder}/${filename}`;
  const resolvedFile = resolveSpecFile(filepath);
  await writeTestcase(resolvedFile, {
    $schema: "../../schema/testcase.json",
    type: "parseError",
    description: `${char} may not be used in an id`,
    template: `{{a${char}b}}`,
  } as HandlebarsTest);
  await addResultToFile(resolvedFile);

  indexFile += `[${filename}](./${filename})\n`;
}

await fs.writeFile(
  resolveSpecFile(`${folder}/WARNING.txt`),
  `WARNING: The files in this folder where GENERATED by "${me}"`
);

await fs.writeFile(resolveSpecFile(`${folder}/index.md`), indexFile);
