name: Test, Build and Publish
on: [push]
env:
  WEBSITE_DIR: packages/@handlebars-ng/specification
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn
      - run: yarn test-and-build

  build-site:
    runs-on: ubuntu-latest
    needs: test-and-build
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          cd ${{ env.WEBSITE_DIR }}
          yarn
          yarn site:build
      - uses: actions/upload-pages-artifact@v1
        with:
          path: "${{ env.WEBSITE_DIR }}/dist/"

  deploy-site:
    if: github.ref == 'refs/heads/main'
    needs: build-site
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1